services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: true

    BD\EzPlatformQueryFieldType\Controller\QueryFieldController: ~

    BD\EzPlatformQueryFieldType\API\QueryFieldService: ~
